// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

namespace Project.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210610171738_Add_Data")]
    partial class Add_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Models.Education", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EducationContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Education");

                    b.HasData(
                        new
                        {
                            ID = new Guid("57ea92ff-5ac7-4f49-b327-08aa85ac132c"),
                            EducationContent = "Multe-s",
                            EducationTitle = "Nvidia GTX1650",
                            PublicationDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Project.Models.Environmental", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnvironmentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentTile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Environment");
                });

            modelBuilder.Entity("Project.Models.Funerals", b =>
                {
                    b.Property<int>("FuneralsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FuneralsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuneralsTile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuneralsId");

                    b.ToTable("Funerals");
                });

            modelBuilder.Entity("Project.Models.Politics", b =>
                {
                    b.Property<int>("PoliticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PoliticsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticsTile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliticsId");

                    b.ToTable("Politics");
                });

            modelBuilder.Entity("Project.Models.Sports", b =>
                {
                    b.Property<int>("SportsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SportsContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportsTile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportsId");

                    b.ToTable("Sports");
                });
#pragma warning restore 612, 618
        }
    }
}
